### ISSUE TITLE
Changing UINavSlider MinValue and MaxValue produces wrong results

### ISSUE THREAD

**Issue by kimsch** [goncasmage1/UINavigation#137]
It seems as if though changing the MinValue and MaxValue to anything but 0 and 1 respectively will produce unexpected results, both with the visual representation of the slider and getting the results from the slider. I tried to understand the process from opening up UINavSlider.cpp but I couldn't figure it out. I'm no expert, but the way I would go about it is working with the slider in a 0 to 1 range and then only in the GetSliderValue function would I remap it to the range set by the MinValue and MaxValue variables. Hope this helps!

**Comment by goncasmage1** [comment]
Hey there 😄 
The Min and MaxValue properties of the UINavSlider can absolutely be values other than 0 and 1 respectively. Many examples in the plugin and the UINav Simple Pack go from 0 to a variety of numbers. I just tried doing a configuration from -5 to 5 and it works as intended, with the slider being in the middel when the value is 0, to the left when it's -5 and to the right when 5. Tested this with an Interval of 1.

The idea is you specify the actual range and the interval of the slider and the plugin will figure out the "percentage" from 0 to 1 from that.

**Comment by kimsch** [comment]
Sorry, you're right. I don't know why it didn't work correctly for me earlier, but I tried it now and it does work correctly now. Might have been some Unreal cache thing that got cleared out in a restart, because now I cannot reproduce it any more. :)
