### ISSUE TITLE
UINavSlider spinbox does not get rounded to nearest Interval.

### ISSUE THREAD

**Issue by kimsch** [goncasmage1/UINavigation#138]
This makes it possible for a user to enter unintended values. 

I made a quick and dirty rounding modification in the UUINavSlider::Update() method, and it works while dragging the SpinBox, but for some reason, it does not when manually entering a number with decimals and pressing enter. 

```
if (NavSpinBox != nullptr)
{
bIgnoreSpinBoxCommit = true;

const float Rounded = FMath::RoundToFloat(Value / Interval) * Interval;
NavSpinBox->SetValue(Rounded);
}
```

**Comment by goncasmage1** [comment]
Can you give me a repro case where the spinbox doesn't get rounded to the nearest interval?

**Comment by kimsch** [comment]
> Can you give me a repro case where the spinbox doesn't get rounded to the nearest interval?

Hi, I just created a new 4.26 project, added the UI Navigation plugin from the Plugins window, then set up the Player Controller and an empty map that spawns a UINav Widget as a container, then dragged a Slider from the examples into it. With a range of 0 to 1 and interval of 0.2, I managed to get non-rounded numbers like these by dragging in the spinbox. Note that it also doesn't update the slider to the spinbox value.

[https://i.imgur.com/KWfjNMo.png](https://i.imgur.com/KWfjNMo.png)

It seems like every second time I drag the spinbox, it rounds and updates properly.

**Comment by goncasmage1** [comment]
The part where it seems like it only clamps every 2nd time you update the spin box is a thing 😂 this is a workaround for a bug in UE4 that was since fixed in 4.25. Got the fix and will push it soon.

Regarding the other issues you mentioned, what would be the intended result in your perspective?

**Comment by kimsch** [comment]
Other than that, it works perfectly! The only other unrelated thing I could ask for (and this goes for all the widgets, such as OptionBox too) is to have a multicast delegate that broadcasts whenever the value is changed (with the new value as parameter), since you typically want things to happen when the slider is changed. With a delegate, that makes it easily accessible to the UMG graph.

**Comment by goncasmage1** [comment]
Unfortunately, most events in the plugin don't have a delegate, just an event, and that does have an event: OnUpdated will be called everytime the value of the UINavSlider changes or the current option of the UINavOptionBox changes 👍
