### ISSUE TITLE
Selector does not properly follow UINavButton contained in Scroll Box

### ISSUE THREAD

**Issue by TheHoodieGuy02** [goncasmage1/UINavigation#140]
The Selector widget often misaligned with the navigated button if it's contained within a Scroll Box. This might have something to do with the selector not updating every frame, with the selector position assumes the button position before the Scroll Box moved into view.
![image](https://user-images.githubusercontent.com/26211033/127253533-046af3eb-beb7-4724-8385-ec0443a6641b.png)

**Comment by TheHoodieGuy02** [comment]
I was using the wrong outdated version of the plugin, didn't notice that the issue is resolved in the newer version. Apologies for the mistake, closing...

**Comment by TheHoodieGuy02** [comment]
Decided to reopen the issue:
While the new version no longer misalign for UINavButtons inside scroll box, it's still going to misalign if the scroll box is animated (albeit less severe).

![image](https://user-images.githubusercontent.com/26211033/129310538-855e9003-2f2e-4211-b568-b503c4ed24be.png)

I might able to resort to my own hack of having separate visible visual widget and hidden functional widgets for the menus, but I want to know if this can be resolved within the plugin.

**Comment by goncasmage1** [comment]
This has since been fixed
