### ISSUE TITLE
Error in UINav PC Component: Not all Menu INputs have been setup!

### ISSUE THREAD

**Issue by lotsofbugs** [goncasmage1/UINavigation#17]
What's this error message? It happened after I update but I couldn't find anything about it.

**Comment by goncasmage1** [comment]
This message means you haven't setup all the Menu Input Actions (MenuSelect, MenuUp, etc.)
If you have any questions, watch this video: https://www.youtube.com/watch?v=T1okpz8xJwM&list=PLAcWSem_HT4hT-3viMU2_z4WW94gKhgn0&index=2&t=1s
