### ISSUE TITLE
Should swap GetDefault and GetMutableDefault?

### ISSUE THREAD

**Issue by josator** [goncasmage1/UINavigation#171]
I think in these lines:

https://github.com/goncasmage1/UINavigation/blob/6161c06bc8220dbaaa53c6c887ce196d4e176cfb/Source/UINavigation/Private/UINavBlueprintFunctionLibrary.cpp#LL98C1-L99C106

Settings should get the pointer with GetMutableDefault, while DefaultUINavInputSettings should get the pointer with getDefault, because the settings being modified are in the "Settings" variable.

The immutable pointer is not apparently giving any error. I am not totally sure.

**Comment by goncasmage1** [comment]
Yes, I'll fix this in the current update. Thanks for pointing this out!
