### ISSUE TITLE
Linked error on static function UUINavWidget::GetOuterObject

### ISSUE THREAD

**Issue by AdrianJC-TheBreachStudios** [goncasmage1/UINavigation#172]
UUINavWidget::GetOuterObject is a templarized function, those can cause issues with unreal if implemented in the .cpp

Found some information about it [here](https://forums.unrealengine.com/t/is-it-possible-to-add-a-function-with-template-in-ue4/57694) and moving everything to the header fixed the linked error.

The file is located at Source\UINavigation\Public\UINavWidget.h

**Comment by goncasmage1** [comment]
Thanks for letting me know!
Just fixed this on GitHub 👍
