### ISSUE TITLE
Avoid updating when trying to go left while in first option without loop (UINavComponentBox)

### ISSUE THREAD

**Issue by AlvaroRR-TheBreachStudios** [goncasmage1/UINavigation#173]
https://github.com/goncasmage1/UINavigation/blob/c86e4495d8bf8d49d2d8511c8e7e61af8d9f38e3/Source/UINavigation/Private/UINavComponentBox.cpp#L64-L65

Just adding `else return;` will behave like NavigateRight. Thank you!

**Comment by goncasmage1** [comment]
Done 👍 
Thanks for pointing out the issue!
