### ISSUE TITLE
IsUINavInputAction will return true when InputActions is null pointer.

### ISSUE THREAD

**Issue by josator** [goncasmage1/UINavigation#186]
https://github.com/goncasmage1/UINavigation/blob/c9ea40619d1c1b2f319c5a726a589789c686ec8f/Source/UINavigation/Private/UINavBlueprintFunctionLibrary.cpp#L170-L178

Short circuit logic for InputActions== nullptr || is fine

But function will return true when InputActions is null pointer.

**Comment by goncasmage1** [comment]
If InputActions is nullptr, you have bigger problems than this function returning true 😅

**Comment by josator** [comment]
It should print a debug message in non-shipping build and return false in such case. It's just an extra if .

**Comment by goncasmage1** [comment]
Will change it to return false if it's nullptr.
If this is not set, you will not be able to navigate the widgets with directional input, so you would probably notice that first 😅
