### ISSUE TITLE
Unused delegate type in UINavPCComponent

### ISSUE THREAD

**Issue by josator** [goncasmage1/UINavigation#189]
This delegate type seems no longer used in the project. I search for it and it does not appear anywhere, I comment it and compiles without errors: 

https://github.com/goncasmage1/UINavigation/blob/bbc971b8ef4b50a0fcc2dc7e177f043248a4cd26/Source/UINavigation/Public/UINavPCComponent.h#L29

**Comment by goncasmage1** [comment]
Thanks for pointing this out!
Will remove in the next update 👍
