### ISSUE TITLE
Cannot Create Two Instances of UINavPlayerController

### ISSUE THREAD

**Issue by MorganWalkup** [goncasmage1/UINavigation#19]
Problem:
I have a scene that creates two instances of UINavPlayerController onBeginPlay (for a local multiplayer game). Before the scene starts, the editor crashes.

Environment:
I'm running UE4.22 on Windows 10 64-bit.
I have a blank project with a blank scene.
The scene uses a custom game mode that creates player 0 and player 1 on BeginPlay.
The custom game mode uses UINavPlayerController as its default controller class.

Error Message:
![UINavCrash](https://user-images.githubusercontent.com/13771986/63141283-d0cdbb00-bfaa-11e9-9cc9-813f4c3d7a31.PNG)

Potential Solutions:
The error points to a "BindAction" problem. Maybe it could be solved by setting up some additional actions in the project settings? Something is going wrong on input for the second player.

**Comment by goncasmage1** [comment]
Hi there :)
Thanks for bringing this to my attention!

Do you have 2 input devices? Because if you don't, that might originate the
error.
Even if you have a keyboard/mouse and a gamepad, if you don't go to your
project's input settings and set Skip Assigning Gamepad to Player 1 (which
is in the Maps & Modes -> Local Multiplayer section), it will still only
control a single character with a gamepad, instead of one with the gamepad
and the other with a keyboard & mouse.

Can you verify both these steps and then please let me know if these fixed
the issue? That would really help me track down the reason why this is
happening.

Cheers.

Morgan Walkup <notifications@github.com> escreveu no dia sexta, 16/08/2019
à(s) 04:22:

**Comment by MorganWalkup** [comment]
I have two xbox one controllers turned on and connected to my PC, but I'm still getting the crash with the same error.

Turning on "Skip Assigning Gamepad to Player 1" also has no effect. The game still crashes and displays the same error.

**Comment by MorganWalkup** [comment]
I also have "Use Splitscreen" set to false in my project settings. Turning it on doesn't seem to change anything, but it could be relevant.

**Comment by goncasmage1** [comment]
Can you tell me the version of the plugin you currently have?

**Comment by MorganWalkup** [comment]
I downloaded the plugin from the marketplace last week, on August 8. I can’t find a specific version number on the marketplace page

**Comment by goncasmage1** [comment]
Can you tell me how you're creating two instances of UINavPlayerControllers?

**Comment by MorganWalkup** [comment]
In my GameMode, on BeginPlay. I use the Create Player node twice to create two instances of the player controller.

I can put together a small project that replicates the issue and send it to you.

**Comment by goncasmage1** [comment]
That would be excellent :) I'd really appreciate that!

Thanks.

**Comment by MorganWalkup** [comment]
Here's a super small project demonstrating the problem. Thank you for your help!
[UINavCrash.zip](https://github.com/goncasmage1/UINavigation/files/3511520/UINavCrash.zip)

**Comment by goncasmage1** [comment]
I've found a fix, I simply had to add a null check to the Input Component.
Again, thanks for bringing this to my attention :)

**Comment by MorganWalkup** [comment]
Easy enough! Thanks again.
Do you have an estimate on when that fix will be available in the marketplace?

**Comment by goncasmage1** [comment]
Not really :/
I've been adding some updates that are done for now, but don't want to rush
them. Maybe i'll update it next week.

A sábado, 17/08/2019, 16:34, Morgan Walkup <notifications@github.com>
escreveu:

**Comment by goncasmage1** [comment]
Just want to let you know that I've just submitted an update with this fix
(along with some others). It will most likely be live early next week :)

Gonçalo Marques <goncalo.alex.marx@gmail.com> escreveu no dia sábado,
17/08/2019 à(s) 17:01:
