### ISSUE TITLE
If-else-if not updated

### ISSUE THREAD

**Issue by josator** [goncasmage1/UINavigation#190]
https://github.com/goncasmage1/UINavigation/blob/bbc971b8ef4b50a0fcc2dc7e177f043248a4cd26/Source/UINavigation/Private/UINavComponent.cpp#L425
https://github.com/goncasmage1/UINavigation/blob/bbc971b8ef4b50a0fcc2dc7e177f043248a4cd26/Source/UINavigation/Private/UINavComponent.cpp#L441
https://github.com/goncasmage1/UINavigation/blob/bbc971b8ef4b50a0fcc2dc7e177f043248a4cd26/Source/UINavigation/Private/UINavComponent.cpp#L455-L457
This sequence of if-else-if should be:

`if      (InNavigationEvent.GetNavigationType() == EUINavigation::Next) {...}`
`else if (InNavigationEvent.GetNavigationType() == EUINavigation::Previous) {...}`
`else if (InNavigationEvent.GetNavigationType() != EUINavigation::Invalid) {...}`

**Comment by goncasmage1** [comment]
Good catch. Don't know how I missed this 😅 
Thanks!
