### ISSUE TITLE
Localization Gather Text not working when enabling UINavigation Plugin

### ISSUE THREAD

**Issue by pelotyo** [goncasmage1/UINavigation#206]
![image](https://github.com/goncasmage1/UINavigation/assets/70829419/12ae930e-65a5-4fb7-8068-bbc89bb09796)

**Comment by pelotyo** [comment]
I'm using newest version.

**Comment by goncasmage1** [comment]
I'm not super familiar with this, but I see no reason for this not to work because of the plugin 🤔

**Comment by pelotyo** [comment]
I'm using UE 5.2.1.
I tried to test in new project to see if the problem was in my project. The gather text worked but with plugin enable doesn't work .
I tried using 3.1.2 back was fine with gather text but occurred navigation bug's .That's why I downloaded the newest version.

It's weird cause 3.1.2 worked and I remembered that 3.1.2 was from epic games launcher. So the plugin is directly inside engine runtime folder.

If that is the case I thought putting the newest version inside runtime folder will work. And it seems to work I don't know why but inside Plugin folder didn't worked for me.
Sometimes didn't show up anything but reopening the tool fix the problem.
I don't check the result of localization yet but at least compile and gather text worked and log text showed up with no problem,

I'm sorry for bothering you, but I think this submission issue could help some people around the internet.
![image](https://github.com/goncasmage1/UINavigation/assets/70829419/e9897dab-1ede-4e8c-aeed-7629f6b28554)

![image](https://github.com/goncasmage1/UINavigation/assets/70829419/974b73ba-50d5-437c-a583-c4ecdf62d666)

**Comment by goncasmage1** [comment]
Alright, seems like just some UE5 weirdness, since my plugin doesn't touch anything related to how Text is handled or localization 😅

**Comment by pelotyo** [comment]
I know it's already closed but to fix the miss information ,I will add some better solution that I have found later as description here.
I thought the same thing that the plugin it self has nothing to do with text stuff, 
So I tried to put 3.7.2 in the plugins folders again, and this time I change the .uplugin "EngineVersion" property to 5.2.0 the problem was fixed.

Adding in runtime folder is not the best solution, if you are not lucky you can't get the newest version popup and it has possibility of causing unknown error when packaging.

**Comment by goncasmage1** [comment]
What was the engine version before, 5.3? Which version of the engine are you using?

**Comment by pelotyo** [comment]
I'm using 5.2.1.

**Comment by goncasmage1** [comment]
Was the version of the plugin 5.3.0 before you changed it?

**Comment by pelotyo** [comment]
Yes
