### ISSUE TITLE
Consider adding to this **if** the same checks present in UUINavComponent::NativeOnFocusChanging

### ISSUE THREAD

**Issue by josator** [goncasmage1/UINavigation#208]
https://github.com/goncasmage1/UINavigation/blob/0252da4c30c264467dfb47c0c1ac522af0292d41/Source/UINavigation/Private/UINavWidget.cpp#L537

```
	if (IsValid(CurrentComponent) || !NewWidgetPath.IsValid() ||
		UINavPC->GetInputMode() == EInputMode::Game ||
		(InFocusEvent.GetCause() == EFocusCause::Mouse &&
		UINavPC->GetInputMode() == EInputMode::GameUI &&
		GetDefault<UUINavSettings>()->bAllowFocusOnViewportInGameAndUI))
```

If not when SetFocus() is called It can cause the same issues it was causing in the other function.

**Comment by goncasmage1** [comment]
Thanks for the reminder! Will add these checks in the next plugin update 👍
