### ISSUE TITLE
Incompatibility between "Force Navigation" and "Use Component Animation"

### ISSUE THREAD

**Issue by souvey** [goncasmage1/UINavigation#209]
Unreal v5.3.2, UINavigation v3.8.4 (from Github, not Marketplace)

Minimal repro:
1) Create an empty-ish new project (I just used the First Person Blueprint template)
2) Set the PlayerController to UINavPC_WPause
3) Set "Use Component Animation" to True on the buttons in UINavPauseMenu
4) Set "Force Navigation" to False in Project Settings
5) Enter play mode and press tab to open the pause menu
6) Move the mouse (in the middle of the screen, not over the buttons) and observe that **the animation plays in reverse for the first menu item: the unforce here should be using bFinishInstantly/RevertAnimation**
7) Click to focus (this is a minor bug in UINavPC_WPause, which doesn't use "Go To Widget"; not terribly important since it's just an issue with the example, not the underlying library)
8) Hover over the first menu item, correctly triggering the animation
9) Press "down" on the keyboard (the S key, by default) and observe that **the first menu item did not play the reverse animation and is now stuck in the wrong state** (in this example/screenshot: the text is still the larger font size)
![image](https://github.com/goncasmage1/UINavigation/assets/1447739/1c4d8f02-9cf7-4c16-a8cd-fe948bd5c30c)

From the logging I've added, the second issue seems to be caused by `bHoverRestoredNavigation`, though I don't really understand what all these state variables are meant to be tracking, so I don't have a proposed fix at this time.

**Comment by goncasmage1** [comment]
Thanks for reporting both these issues!
I was able to reproduce them and fixed them in the last commit.
If this didn't fix the issue for you, be sure to respond to this issue.
For now, I'll close it.
