### ISSUE TITLE
Issue with multiline messages and RichText

### ISSUE THREAD

**Issue by josator** [goncasmage1/UINavigation#210]
https://github.com/goncasmage1/UINavigation/blob/1f906c8fbc66a3903511062aafc3146a53ea0f52/Source/UINavigation/Private/UINavBlueprintFunctionLibrary.cpp#L171

I am on 5.3 and I am experiencing issues with multiline messages parsed with this function. This kind of output shows wrong formatting. ie:

```
<WhiteMedium>Space Bar is already being used by Dodge.
</>
<WhiteMedium>Do you want to swap it with Left Alt? </>
```
Should be fine but causes first line to not be parsed properly. At least in my engine version.

Adding .TrimEnd() to remove whitespace linebreaks after split fixes it:

		FinalString += TEXT("<") + StyleRowName + TEXT(">") + StringArray[i].TrimEnd() + TEXT("</>");

```
<WhiteMedium>Space Bar is already being used by Dodge.</>
<WhiteMedium>Do you want to swap it with Left Alt?</>
```

**Comment by goncasmage1** [comment]
Thanks for reporting this!
Just fixed this in the latest commit.
Let me know if you find other issues. 💪
