### ISSUE TITLE
Chain Navigation stuck if widget if destroyed while key is pressed

### ISSUE THREAD

**Issue by souvey** [goncasmage1/UINavigation#211]
Unreal v5.3.2, UINavigation v3.8.4

Minimal repro:
1. Create an empty-ish new project (e.g. First Person Blueprint template) with PlayerController set to UINavPC_WPause
2. Enter play mode and press menu key (Tab); pause menu should appear
3. Hold down the down navigation key (D); menu should chain navigate to the last option
4. While still holding the down key, press the menu key (Tab) at the same time; menu should disappear
5. Release the down navigation key (D)
6. Press menu key (Tab) to reopen the menu; **the menu behaves as though D is still pressed**

This is because UINavPCComponent relies on NotifyNavigationKeyReleased being called by UINavComponent::NativeOnKeyUp, but this never happens because the widget does not exist / is not receiving events when the key is released.

**Comment by goncasmage1** [comment]
Thanks for reporting this 👍 
This should be fixed in the latest version.
Let me know if you find any other issues 💪
