### ISSUE TITLE
OnNavigatedSound doesn't take into account unforced navigation

### ISSUE THREAD

**Issue by souvey** [goncasmage1/UINavigation#221]
Repro project: new blank project with https://www.unrealengine.com/marketplace/en-US/product/ui-navigation-simple-pack-3 and the latest UINavigation from github; "Force Navigation" set to false in settings.

On play, the menu select tick sound plays immediately, even though nothing is visibly selected.
Mouse hovering over the first menu item plays no sound (because internally it's already been navigated to)
Similarly, moving the mouse to the last menu item plays a tick, but then moving the mouse off of it, and then back onto it, doesn't play a tick.

I would expect the tick sounds to match with the visible state (i.e. the forced/unforced state, as is used for animations, color, selector, etc), not the internal navigation state

**Comment by goncasmage1** [comment]
Thanks for reporting this!

I was able to reproduce and fix the issue 👍 will go live in the next update.
