### ISSUE TITLE
Can't use the plugin in assets used from C++

### ISSUE THREAD

**Issue by lalomartins** [goncasmage1/UINavigation#3]
I have a game mode in C++ which references a HUD defined in BP, which in turn uses an UMG Widget Blueprint.

Now, I don't know if that's a bad idea for other reasons — I'm a beginner — but it's working so I'll stick with it for now.

However, next time I started the editor after making that change, it gave me errors on load. `Can't find file for asset. /Script/UINavigation`. The reason for that is that project C++ files are loaded before  the Standard loading phase.

I edited `UE_4.21\Engine\Plugins\Marketplace\UINavigation\UINavigation.uplugin` and changed:

```json
"LoadingPhase": "Default",
```
to
```json
"LoadingPhase": "PreDefault",
```

and now it works. Thanks [the intahwebs](https://answers.unrealengine.com/questions/459944/cant-find-file-for-asset-scriptcablecomponent-on-4.html) for the solution.

**Comment by goncasmage1** [comment]
Thanks for letting me know! I'll make this modification.
