### ISSUE TITLE
Some keyboard buttons will cause the first OnSelect event to not trigger after the first opening

### ISSUE THREAD

**Issue by Levitikon217** [goncasmage1/UINavigation#33]
Okay, this is a strange issue and I'm sure the title is a little confusing so I'll walk through it simply so its understood because it took me a while to isolate it. The attached project is a super simple example that also reproduces the issue so hopefully there's no confusion.

In TestPlayerController there are 2 key bindings that Create a Widget/Add to Viewport a UINavWidget with some buttons. These bindings are Spacebar and the P key.

1) Run project
2) Press P key
expected: menu opens
actual: menu opens

The buttons in the menu UINavWidget are configured to exit the menu via any OnSelect event.
3) Press Enter key
expected: menu closes
actual: menu closes

4) Press P key
expected: menu opens
actual: menu opens

5) Press Enter key
expected: menu closes
actual: **menu does not close**

5) Press Enter key again
expected: menu closes
actual: menu closes

When ever the menu opens after the first round of open/close, the first Enter key event does not trigger the OnSelect event, but only when opening the menu with certain keys. It does always trigger the KeyDown event, so something is blocked in between KeyDown and OnSelect. My guess is the stuff in OnPreSelect.

If however, the spacebar is used to open the menu, there are never any issues. I have noticed the P key and Delete key to cause this behavior. Might be more, I haven't tested others.

[UINavigationFocusBug2.zip](https://github.com/goncasmage1/UINavigation/files/3647977/UINavigationFocusBug2.zip)

**Comment by goncasmage1** [comment]
Ok I was finally able to reproduce and fix this bug!
It had to do with the internal state of the UINavPCComponent.

Thanks for bringing this to my attention! :)

**Comment by goncasmage1** [comment]
It won't be live on the next update, but on the one after that

**Comment by Levitikon217** [comment]
Awesome. Glad it wasn't just my imagination :D
