### ISSUE TITLE
Buttons of child menu not focused when parent removed?

### ISSUE THREAD

**Issue by Levitikon217** [goncasmage1/UINavigation#34]
When opening a child menu from a parent menu using Go to Widget when Removed Parent is checked will cause the buttons of the child menu not to be navigable by the keyboard. See attached project. Here are the repro steps:

1) Ensure Remove Parent checkbox in Go to widget in Test Menu is un-checked
![image](https://user-images.githubusercontent.com/1824102/65557918-f089c480-df02-11e9-8996-f0f1ee3b94a6.png)

2) Run project
3) Press Spacebar to open parent menu
4) Press Enter to open child menu
5) Press W or S
Expected: button changes
Actual: button changes
6) Stop project

1) Now, Toggle the Remove Parent checkbox in Go to widget in Test Menu to be checked
![image](https://user-images.githubusercontent.com/1824102/65557966-1fa03600-df03-11e9-98e5-eaad51d3fb21.png)

2) Run project
3) Press Spacebar to open parent menu
4) Press Enter to open child menu
5) Press W or S
Expected: button changes
Actual: button do not change

[UINavigationChildFocusWhenRemoveParent.zip](https://github.com/goncasmage1/UINavigation/files/3649893/UINavigationChildFocusWhenRemoveParent.zip)

**Comment by Levitikon217** [comment]
So I went back through some documentation videos to see if this is just me setting things up incorrectly and I think I see where our paths deviate.

Where I [Set Game Paused], [Set Input Mode UI Only],
You        [Set Ignore Look Input], [Set Ignore Move Input], and [Set Input Mode Game and UI]

Swapping [Set Input Mode UI Only] for [Set Input Mode Game and UI] seems to resolve the issue. So [Set Input Mode UI Only] is the root cause here.

**Comment by goncasmage1** [comment]
Yes I also noticed that when testing the plugin a while back.
For some reason, when Input Mode is set to UI Only, neither the Player
Controller will receive inputs neither the widget will receive key presses
through the OnKeyDown event.
I'll have to investigate this further, but it is a known issue on my part.

A quarta, 25/09/2019, 11:50, Levitikon <notifications@github.com> escreveu:

**Comment by goncasmage1** [comment]
I have found a fix for this!
Apparently, I not only have to SetUserFocus, but also KeyboardFocus.
Will be fixed in the update after the next.
Thank you for bringing this to my attention :)

**Comment by Levitikon217** [comment]
Awesome. Glad to be of service.
