### ISSUE TITLE
Help with unusual buttons layout

### ISSUE THREAD

**Issue by lotsofbugs** [goncasmage1/UINavigation#4]
Hello. First of all, thanks for your marvelous plugin, it's helping me a lot!
I'm making a virtual keyboard for my game but I don't know which navigation method to use. Grid, Vertical and Horizontal doesn't work. Any out-of-the-box solution?

![image](https://user-images.githubusercontent.com/23303304/54149219-6e2d2d80-4414-11e9-9773-c3a65425bcea.png)

**Comment by goncasmage1** [comment]
Hmm I'm afraid there's no out of the box solution for that.
Either setup each row as a horizontal grid and then allow the player to navigate down to a specific button of the next grid, or simply edit the individual ButtonNavigations of each of those buttons :/

Keep in mind that the plugin will change a bit in that regard when 2.0 is introduced. You can see the video in the marketplace page's description for more info.

Cheers!
