### ISSUE TITLE
[Bug] typo

### ISSUE THREAD

**Issue by piomerti** [goncasmage1/UINavigation#42]
Lazy to pull, so...
UINavWidget.cpp:1040

**Comment by goncasmage1** [comment]
Can you give my a little more information than that? 😅

**Comment by piomerti** [comment]
`bool bShouldNavigate = bAutoNavigate && ButtonIndex >= FirstIndex && ButtonIndex <= ButtonIndex;`
Can’t you see the error? ButtonIndex <= ButtonIndex?

**Comment by goncasmage1** [comment]
Now I can!
Sorry I didn't look at it too attentively 😅 
Thanks for letting me know!
