### ISSUE TITLE
[Bug] broken fullscreen buttons 

### ISSUE THREAD

**Issue by piomerti** [goncasmage1/UINavigation#43]
Fix  FS buttons (Alt+Enter & F11)
`if (GEngine && GEngine->GameViewport &&
	GEngine->GameViewport->TryToggleFullscreenOnInputKey(InKeyEvent.GetKey(), IE_Pressed))
	return FReply::Handled();`
at the beginning of the function UUINavWidget::NativeOnKeyDown works for me

**Comment by goncasmage1** [comment]
Can you specify what issue this solves?

**Comment by piomerti** [comment]
Well, Toggle Fullscreen/Window Mode on input key (F11 and Alt+Enter). When your widget is active it just does not work.

**Comment by goncasmage1** [comment]
Again, thanks for letting me know ❤️
