### ISSUE TITLE
Editor crash

### ISSUE THREAD

**Issue by shukenmg** [goncasmage1/UINavigation#51]
The editor crashes with this error
`UE4Editor_UINavigation!TMapBase<FString,TArray<FKey,TSizedDefaultAllocator<32> >,FDefaultSetAllocator,TDefaultMapHashableKeyFuncs<FString,TArray<FKey,TSizedDefaultAllocator<32> >,0> >::GenerateKeyArray<TSizedDefaultAllocator<32> >() [A:\Program Files\Epic\UE_4.23\Engine\Source\Runtime\Core\Public\Containers\Map.h:546]
UE4Editor_UINavigation!UUINavPCComponent::FindActionByKey() [E:\Coding\UE4Projects\UiNav\Plugins\UINavigation-2.14.0\Source\UINavigation\Private\UINavPCComponent.cpp:606]
UE4Editor_UINavigation!UUINavWidget::OnKeyReleased() [E:\Coding\UE4Projects\UiNav\Plugins\UINavigation-2.14.0\Source\UINavigation\Private\UINavWidget.cpp:480]
UE4Editor_UINavigation!UUINavWidget::NativeOnMouseButtonUp() [E:\Coding\UE4Projects\UiNav\Plugins\UINavigation-2.14.0\Source\UINavigation\Private\UINavWidget.cpp:460]`

Do you know why this happens?
Or is it possible to fix it?

Thanks

**Comment by shukenmg** [comment]
So this bug seems to be caused when a widget is reused in between levels, thus causing the controller to be changed then once the controller has been changed once, the widget fails to set it again because the Nav setup is only run once throughout the lifetime of the widget.

**Comment by shukenmg** [comment]
@goncasmage1 Hello, 
Will you update the plugin for 4.23 with this fix?

Thanks.

**Comment by shukenmg** [comment]
I just saw the fix in the 4.24 branch.
Now that's a much better fix than I did haha.

Good job.

**Comment by goncasmage1** [comment]
Thanks 😄 unfortunately I don't plan on doing the fix for 4.22 or 4.23.
I already submitted the 4.24 version, which should be live early this week, so I'm dropping support for 4.22 and 4.23.

**Comment by shukenmg** [comment]
@goncasmage1 Oh really, that's unfortunate.
Would you mind telling me how to package the plugin for sharing?
I built the plugin with the fix for 4.23 and it works on my PC but is unable to load on a different PC.
But the plugin downloaded from the marketplace works.
Why is that?

**Comment by goncasmage1** [comment]
In order to package the plugin, you have to go to the Plugins window and select Package on the UI Navigation plugin.

**Comment by shukenmg** [comment]
@goncasmage1 Oh ok, thank you I will try it out
