### ISSUE TITLE
Unable to package.

### ISSUE THREAD

**Issue by shukenmg** [goncasmage1/UINavigation#53]
Unable to package with Shipping Win64 and nativize blueprints.
This happens when attempting to use the plugin only in the project folder and not from the Engine install.
Attempting to package will cause errors saying that headers can't be found.

The workaround, for now, is to copy the plugin to the Engine plugins directory.

Maybe make an option for the plugin to be used in the project folder?

**Comment by goncasmage1** [comment]
In which engine version does this happen?

**Comment by goncasmage1** [comment]
Bump

**Comment by shukenmg** [comment]
@goncasmage1 Sorry, was a bit busy.
This happens on 4.23 but probably happens on 4.24, I will test it soon.

**Comment by goncasmage1** [comment]
Let me know if this still happens in 4.24 :)

**Comment by goncasmage1** [comment]
Bump

**Comment by shukenmg** [comment]
@goncasmage1 
Initial testing throws this error on 4.24.
`UATHelper: Packaging (Windows (64-bit)):   E:/Redacted/Intermediate/Plugins/NativizedAssets/Windows/Game/Source/NativizedAssets/Private/UINavOptionsMenuWKeybinds__pf3962297051.cpp(4069): error C2248: 'UUINavComponentBox::UpdateTextToIndex': cannot access protected member declared in class 'UUINavComponentBox'
UATHelper: Packaging (Windows (64-bit)):   e:\redacted\uinavigation\source\uinavigation\public\UINavComponentBox.h(26): note: see declaration of 'UUINavComponentBox::UpdateTextToIndex'`

**Comment by shukenmg** [comment]
This is when packaging with blueprint nativization set to Inclusive

**Comment by shukenmg** [comment]
Will test with a more complete project soon

**Comment by goncasmage1** [comment]
Ok here's the thing, I'm also getting errors when packaging the plugin with nativization set to inclusive, but that feature is well known to have its bugs and the errors I'm getting make no sense, so what I'd suggest is for you to only nativize the blueprints you really need.

Sorry about that 😦

**Comment by shukenmg** [comment]
@goncasmage1 
It's true, but the way to fix this is to have the plug-in installed in both the project AND engine, I'd you do that then it works

**Comment by goncasmage1** [comment]
At least you know how to fix it 😁
