### ISSUE TITLE
[Bug] UINavPC can be NULL

### ISSUE THREAD

**Issue by piomerti** [goncasmage1/UINavigation#56]
If the player controller changes while the widget exists then UINavPC becomes invalid. For example, this can happen if you create a widget in a singleton (GameInstance). Wrap all calls with getters better.

**Comment by goncasmage1** [comment]
You can now call a UINavWidget function called ConfigureUINavPC, which refetches the UINavPC.
You have to call it on the singleton when the Player Controller changes.
