### ISSUE TITLE
"Not all UINavButtons have a Grid Setup" 

### ISSUE THREAD

**Issue by lotsofbugs** [goncasmage1/UINavigation#67]
Hello!
I know how to properly setup a UI Nav Menu, and it works for all of the menus in my game, minus one. 
It says "Not all UINavButtons have a Grid Setup", but all of them are inside an Horizontal Box and in the Append Navigation 1D - Horizontal, I'm using dimension = -1, so what can be wrong?

Is there a way to debug the plugin?

**Comment by goncasmage1** [comment]
Can you show me your widget setup through email or discord? (discord would be preferable)

**Comment by lotsofbugs** [comment]
Sure, what's your discord?

**Comment by goncasmage1** [comment]
It's in the marketplace page of the UI Navigation plugin
