### ISSUE TITLE
UE 4.24 More then one button selected after Navigate To call

### ISSUE THREAD

**Issue by dazre** [goncasmage1/UINavigation#76]
Hi,

I am trying to use a plugin for a virtual keyboard and I am having some problems. First of all, it is selecting several buttons after Navigate To call.

![Annotation 2020-06-17 212033](https://user-images.githubusercontent.com/803589/84934746-6f9dd900-b0e0-11ea-8fad-674d09b4625a.png)
![Desktop Screenshot 2020 06 17 - 21 21 38 33](https://user-images.githubusercontent.com/803589/84935402-50ec1200-b0e1-11ea-9ac8-0543f9ab57fa.png)

I would like to set up different Edge Navigation for different buttons. For example, after Down at "x" button the "#+=" button need to be selected. And for "c" button Down need to be select "Space". I try to use SetEdgeNavigationByButton but it has no any affect.

**Comment by goncasmage1** [comment]
It seems to me like using the OnNavigate event to call the NavigateTo function will cause a cyclical call, are you sure that's what you want?

In order to change the edge navigation, I'd say doing the same thing that is being done in the Options Menu and changing the grid's EdgeNavigation using the function you mentioned, but doing it on the OnNavigate event, in order to update it depending on which button you're in now.

**Comment by dazre** [comment]
You are right about a loop, but a comparison expressions are prevent a continuous call. So it's ok for me.

I will try and give you feedback.

**Comment by dazre** [comment]
Setup EdgeNavigation:
![1](https://user-images.githubusercontent.com/803589/85013103-af120700-b16c-11ea-95d2-f8888c5daab6.png)

Layout:
![3](https://user-images.githubusercontent.com/803589/85013169-cb15a880-b16c-11ea-8630-4812fc20262a.png)

EdgeNavigation at OnNavigate event:
![2](https://user-images.githubusercontent.com/803589/85013213-e385c300-b16c-11ea-98d9-fa862ca9e6c2.png)

An there is no any effect from SetEdgeNavigationByButton usage. When I press Down at "c" button a selection are still move to "Shift" instead of "Space".

**Comment by goncasmage1** [comment]
The last screenshot doesn't look quite right. What you'll want to do is probably a switch (or some way to identify which index was just navigated to) and then depending on that index, setting a different down button using the SetEdgeNavigationByButton. The Grid Index parameter isn't correct, it should always be the same, the index of the grid that has the QWERTY etc. keys.

**Comment by dazre** [comment]
Yep. I've already found an yours Options Menu example. Thank you.
