### ISSUE TITLE
[BUG] Collection are treated as one button when setting them up before Empty Grid (Filled at Runtime)

### ISSUE THREAD

**Issue by TRI99ERED** [goncasmage1/UINavigation#89]
Description:
When Setting up widget with Collection followed by Empty Grid and then filling Empty Grid with buttons on Runtime, Navigation breaks and instead of treating all buttons in Collection properly, Navigation jumps to Second Grid's buttons if you try to navigate from first button of Collection.
The same way, if you mouse over any other button of Collection and try to Navigate to first button of that Collection, you will jump to last button of Second Grid (although there is no Edge Navigation setup to it).
It somehow treats Second Grid as placed inside of Collection after first button of Collection.

Steps to Reproduce:
1. Create Project and add UINav Inputs to it
2. Add UINav Widget, UINav Collection and UINav Component
3. Inside UINav Widget's Designer add UINav Collection and after that Vertical Box
4. On Ready for Setup Append Collection and then Append Navigation Grid 1D (Vertical) with 0 dimension (Edge Navigation is not necessary and in example project just placed to show intended behavior)
5. On Setup Completed Create arbitrary number of UINav Components and add them to Vertical Box and Empty Grid
5. Inside UINav Collection's Designer add Vertical Box and arbitrary number of UINav Buttons (more than 1)
6. Append Navigation Grid 1D (Vertical) with dimension set to Vertical Box's Children Count
7. Inside UINav Component's Designer Add UINav Button named NavButton
8. Create UINavController and set it inside default GameMode
9. Add main widget to Viewport
10. Start PIE
11. **Try to navigate down from first button inside of Collection**

Expected result:
After pressing Down instead of navigating to the second button of Collection, you will navigate to the first button of the second Grid.

**Comment by TRI99ERED** [comment]
Example Project:
[Test.zip](https://github.com/goncasmage1/UINavigation/files/5616068/Test.zip)

**Comment by goncasmage1** [comment]
@TRI99ERED I wasn't able to repro this in a test with a relatively similar setup, however, I was able to repro this in the project you sent. Thanks for that btw 💪 
This can be fixed (for now) by adding the desired UINavComponents in the PreSetup event, if the FirstSetup boolean is true, and without calling the AddUINavComponent function, which is the recommended setup for these types of widgets.

With that said, it does look like a bug and I'll investigate this further.
Thanks for bringing this to my attention!

**Comment by goncasmage1** [comment]
Update, this bug has already been fixed accidentally among the changes that I've made in the 4.24 branch that are not yet live 😁

**Comment by TRI99ERED** [comment]
When are they expected to release?

**Comment by goncasmage1** [comment]
The next update will go live simultaneously as the 4.26 version releases

**Comment by TRI99ERED** [comment]
> The next update will go live simultaneously as the 4.26 version releases

Still not fixed. Are changes only meant for 4.26 version and 4.25 won't be fixed?

**Comment by goncasmage1** [comment]
Are you fetching the plugin directly from GitHub or from the Epic Games Launcher?

**Comment by TRI99ERED** [comment]
> Are you fetching the plugin directly from GitHub or from the Epic Games Launcher?

In the launcher.

**Comment by goncasmage1** [comment]
Have you tried doing this again after fetching the latest update that went live a few hours ago?

**Comment by TRI99ERED** [comment]
Can confirm it was fixed.
