### ISSUE TITLE
Hover Button style stuck post actioning button if Use Button States is Disabled

### ISSUE THREAD

**Issue by teamtwentythree** [goncasmage1/UINavigation#96]
Simple Repro is to build a simple stack of 3 buttons.  UINav Widget Use Button States should be disabled.

Navigate the menu using a controller.  Select a button.  Once selected the button will be stuck in the hover style.

**Comment by goncasmage1** [comment]
The UseButtonStates boolean is supposed to do what you want to do when you set it to true 😁
