### ISSUE TITLE
UI Navigation Youtube Tutorial does not mention Use Button States or Use Text Color options

### ISSUE THREAD

**Issue by teamtwentythree** [goncasmage1/UINavigation#97]
With neither of these options set there will be no visual when navigating buttons.

**Comment by goncasmage1** [comment]
This is mentioned here: https://youtu.be/w7maDj-mCFM?list=PLAcWSem_HT4hT-3viMU2_z4WW94gKhgn0&t=585
Please watch the videos all the way until the end.
