### ISSUE TITLE
UINav Widget "Use Button States" default value false

### ISSUE THREAD

**Issue by teamtwentythree** [goncasmage1/UINavigation#98]
Expected behavior (From new user and from existing YouTube tutorials) is that when navigating a menu the normal UMG button states are utilized.  The current default value is false which causes them to not be utilized.

Use Text Color is also default false, so by default there is no visual for navigation.

**Comment by goncasmage1** [comment]
There is too much risk with turning this value to true by default now, since so many projects are probably counting on it as false by default. Thanks for the suggestion though!
